-- Table: public.fdp_cases

-- DROP TABLE IF EXISTS public.fdp_cases;

CREATE TABLE IF NOT EXISTS public.fdp_cases
(
    no integer,
    region text COLLATE pg_catalog."default",
    access_case text COLLATE pg_catalog."default" NOT NULL,
    access_case_creation_date text COLLATE pg_catalog."default",
    family_progress_status text COLLATE pg_catalog."default",
    family_progress_comments text COLLATE pg_catalog."default",
    date_of_last_contact text COLLATE pg_catalog."default",
    settlement_cm text COLLATE pg_catalog."default",
    settlement_case_status text COLLATE pg_catalog."default",
    family_last_name text COLLATE pg_catalog."default",
    head_of_family_first_name text COLLATE pg_catalog."default",
    phone text COLLATE pg_catalog."default",
    state_code_2_digits text COLLATE pg_catalog."default",
    zip_code double precision,
    country_of_origin text COLLATE pg_catalog."default",
    number_in_family double precision,
    visa text COLLATE pg_catalog."default",
    asylum_visa_progress text COLLATE pg_catalog."default",
    arrival_date timestamp without time zone,
    initial_point_of_entry text COLLATE pg_catalog."default",
    current_location text COLLATE pg_catalog."default",
    initial_annual_family_income double precision,
    current_annual_family_income double precision,
    current_annual_income_date text COLLATE pg_catalog."default",
    current_annual_enititlement_income double precision,
    current_annual_enititlement_income_date timestamp without time zone,
    fdp_completion_status text COLLATE pg_catalog."default",
    destination text COLLATE pg_catalog."default",
    adults_18_65 double precision,
    ecd_age_children_0_6 double precision,
    kids_6_18 double precision,
    seniors_65 double precision,
    family_structure text COLLATE pg_catalog."default",
    of_boys_between_6_18_yrs double precision,
    of_girls_between_6_18_yrs double precision,
    of_college_age_18_25 double precision,
    social_assessment_completed text COLLATE pg_catalog."default",
    current_housing_situation text COLLATE pg_catalog."default",
    funding text COLLATE pg_catalog."default",
    household_setup text COLLATE pg_catalog."default",
    laptop_internet_access text COLLATE pg_catalog."default",
    access_furniture_support text COLLATE pg_catalog."default",
    qol_housing_do_we_need_to_find_housing text COLLATE pg_catalog."default",
    ssn_received text COLLATE pg_catalog."default",
    health_and_food_stamps text COLLATE pg_catalog."default",
    cm_social_benefits text COLLATE pg_catalog."default",
    driving_test text COLLATE pg_catalog."default",
    sdi_driving_license_lessons text COLLATE pg_catalog."default",
    car_status text COLLATE pg_catalog."default",
    epb_jat_loan text COLLATE pg_catalog."default",
    type_of_job_hoh text COLLATE pg_catalog."default",
    hours_per_week_worked_hoh double precision,
    type_of_job_spouse text COLLATE pg_catalog."default",
    hours_per_week_worked_spouse double precision,
    type_of_job_other_1 text COLLATE pg_catalog."default",
    hours_per_week_worked_other_1 double precision,
    type_of_job_other_2 text COLLATE pg_catalog."default",
    hours_per_week_worked_other_2 double precision,
    epb_jobline text COLLATE pg_catalog."default",
    epb_sbi text COLLATE pg_catalog."default",
    daycare_or_dependent_care_barrier_to_employment text COLLATE pg_catalog."default",
    observed_any_cultural_barriers_for_women text COLLATE pg_catalog."default",
    swb_iwg_other text COLLATE pg_catalog."default",
    highest_education_level text COLLATE pg_catalog."default",
    computer_proficiency text COLLATE pg_catalog."default",
    sdi_skills_development text COLLATE pg_catalog."default",
    external_vocational text COLLATE pg_catalog."default",
    external_community_college text COLLATE pg_catalog."default",
    external_4_year_college text COLLATE pg_catalog."default",
    english_proficiency text COLLATE pg_catalog."default",
    sdi_english_internal text COLLATE pg_catalog."default",
    external_english text COLLATE pg_catalog."default",
    financial_assessment_completed text COLLATE pg_catalog."default",
    jm_has_access_to_financial_resources_banking_cc_etc text COLLATE pg_catalog."default",
    jm_has_excessive_debt_in_us text COLLATE pg_catalog."default",
    epb_flpp text COLLATE pg_catalog."default",
    epb_cu_referrals double precision,
    epb_debt_management double precision,
    subsidy_need text COLLATE pg_catalog."default",
    cm_subsidies text COLLATE pg_catalog."default",
    kids_registered_in_school text COLLATE pg_catalog."default",
    eb_school_enrollment text COLLATE pg_catalog."default",
    school_district text COLLATE pg_catalog."default",
    lc_relocation_snq text COLLATE pg_catalog."default",
    any_academic_issues_observed_or_reported_by_the_family_with_any text COLLATE pg_catalog."default",
    any_issues_challenges_observed_or_reported_with_parental_engage text COLLATE pg_catalog."default",
    youth_esl_tutoring_needed text COLLATE pg_catalog."default",
    eb_academic_support_esl_tutoring_parental_engagement_support_et text COLLATE pg_catalog."default",
    qol_tutoring text COLLATE pg_catalog."default",
    kids_registered_in_ecd text COLLATE pg_catalog."default",
    eb_ecd text COLLATE pg_catalog."default",
    eb_efas double precision,
    any_social_issues_observed_or_reported_for_any_of_the_children_ text COLLATE pg_catalog."default",
    ssn_case_management text COLLATE pg_catalog."default",
    family_can_get_insurance_hoh text COLLATE pg_catalog."default",
    hb_healthcare_literacy text COLLATE pg_catalog."default",
    hb_insurance_pcp text COLLATE pg_catalog."default",
    anyone_in_the_family_disabled_or_has_chronic_illness text COLLATE pg_catalog."default",
    ssn text COLLATE pg_catalog."default",
    any_child_ren_s_health_issues text COLLATE pg_catalog."default",
    akhb_child_health text COLLATE pg_catalog."default",
    kids_registered_in_rec text COLLATE pg_catalog."default",
    itreb_rec text COLLATE pg_catalog."default",
    met_with_mk_s text COLLATE pg_catalog."default",
    access text COLLATE pg_catalog."default",
    vrm text COLLATE pg_catalog."default",
    ysb text COLLATE pg_catalog."default",
    ssn_1 text COLLATE pg_catalog."default",
    family_has_access_to_food_groceries text COLLATE pg_catalog."default",
    access_1 text COLLATE pg_catalog."default",
    hb double precision,
    notes text COLLATE pg_catalog."default",
    arrival_in_us text COLLATE pg_catalog."default",
    final_destination double precision,
    CONSTRAINT fdp_cases_pkey PRIMARY KEY (access_case)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.fdp_cases
    OWNER to "settlementAdmin71125";